### ISSUE TITLE
Only Loading... Please wait... after that show blank page, i'm try o make custom script.

### ISSUE THREAD

**Issue by juragandotid** [bmvantunes/stripe-3d-secure#2]
This is my custom script : 

function onClick() {
var name = document.getElementById('holder').value;
var address_line1 = document.getElementById('address').value;
var address_city = document.getElementById('town').value;
var address_state = document.getElementById('county').value;
var address_zip = document.getElementById('postcode').value;
var address_country = document.getElementById('country').value;
var cardNumber = document.getElementById('ccno').value;
var input = document.getElementById('ccexp').value;
var fields = input.split('/');
var expMonth = fields[0];
var expYear = '20'+fields[1];
var cvc = document.getElementById('secode').value;
  const paymentRequest = {
	name: name,
	address_line1: address_line1,
	address_city: address_city,
	address_state: address_state,
	address_zip: address_zip,
	address_country: address_country,
    cardNumber: cardNumber,
    expMonth: expMonth,
	expYear: expYear,
    cvc: cvc,
    currency: 'usd',
    amount: 100,
    nativeElement: document.querySelector('#iframe-payment')
  };
  
  paymentRequest.nativeElement.innerHTML = 'Loading... Please wait...';

  doPayment(paymentRequest).then((result) => {
    paymentRequest.nativeElement.innerHTML = 'Success!!!! Your details are correct!!!';
    window.location.replace = window.location.protocol + '//' + window.location.hostname + '/success';
  }).catch((error) => {
    console.error(error);
    paymentRequest.nativeElement.innerHTML = 'Ups! We can\t validate your details...';
    alert('Your credit card was declined. Please enter another credit card or check your info');
  });
}

how to make work this script, I'm ready  to set my pk_live.But i got error.Only Loading... Please wait... after that show bank page without any redirect .

Thank you.

**Comment by bmvantunes** [comment]
Can you please create a [stackblitz](https://stackblitz.com/) or [jsfiddle](https://jsfiddle.net/) example? It's easier for me to understand the problem and help you :)

**Comment by juragandotid** [comment]
can u tell me how to your source works?

2018-03-14 4:29 GMT-05:00 Bruno Antunes <notifications@github.com>:

**Comment by bmvantunes** [comment]
Hi,

The loading step can take a few seconds.
Basically, we are waiting for stripe API, and in the case of 3ds cards, for the iframe to load. In a real application, you want a good waiting experience not only a "Loading... Please wait...", but for demo purposes, it does the trick :)

All my logic is super simple. Every time you click a button it calls `onClick` inside main.js. Then it calls `doPayment` inside api.js. The functions inside api.js are presented in order of execution, to make the understanding easier. You can have a closer look at https://github.com/bmvantunes/stripe-3d-secure/blob/master/js/api.js

I hope it helps.

**Comment by juragandotid** [comment]
How do i'm generate token from pk live key? And implementation on your
source code. Thank you.

Pada tanggal 14 Mar 2018 16:29, "Bruno Antunes" <notifications@github.com>
menulis:
